name: Bug Report
description: Help us fix bugs by reporting them here.
"labels": ["Bug"]
type: bug
body:
 - type: textarea
   attributes:
     label: Bug Description
     description: "Please describe the issue in detail."
   validations:
     required: true
 - type: textarea
   attributes:
     label: Reproduction steps
     description: "How do you trigger this bug? Please walk us through it step by step."
     value: |
       1.
       2.
       3.
       ...
     render: bash
   validations:
     required: true
 - type: input
   attributes:
     label: Release Build
     description: "The mod release build number."
     placeholder: "eg: CCTVCraft Utility 5.2.1"
   validations:
     required: true
 - type: input
   attributes:
     label: Minecraft Build
     description: "The Game's Build number."
     placeholder: "eg: Minecraft 1.21.4"
   validations:
     required: true
