blank_issues_enabled: false
contact_links:
  - name: "Wiki"
    url: https://github.com/northwesttrees-gaming/CCTVCraft5Utility/wiki
    about: Documentation can be found on the official wiki pages here on GitHub.
